name: qr_code
description: "QR Code Generator for Almajed4Oud to reviewing branches & employees"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.0-290.4.beta

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  pdf: ^3.11.3
  freezed_annotation: ^3.1.0
  web: ^1.1.1
  font_awesome_flutter: ^10.12.0
  printing: ^5.14.2
  injectable: ^2.7.1+4
  get_it: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  freezed: ^3.2.4
  injectable_generator: ^2.11.1
  gh_pages: ^0.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/logo/

  fonts:
    - family: Alexandria
      fonts:
        - asset: assets/fonts/Alexandria-Regular.ttf
          weight: 400
        - asset: assets/fonts/Alexandria-Bold.ttf
          weight: 700
    - family: Brand
      fonts:
        - asset: assets/fonts/fa-brands-400.ttf
          weight: 400
    - family: Solid
      fonts:
        - asset: assets/fonts/fa-solid-900.ttf
          weight: 900
